import React from 'react';
import PageHeader from '../components/PageHeader';
import product_terms_header from "../images/headers/product_terms_header.png";

const ProductTerms = () => {
  return (
    <div className='common_layout2'>
      <PageHeader header_img={product_terms_header} />
      <div className="section_padding">
        <div className="container">
          <h2>Product Terms</h2>
            <p><strong>Please read this information carefully.</strong><br />
            The download or submission of an order of Products to Australia Wine Merchants Pty Ltd (‘AWM’) by you indicates an acceptance of and agreement to be bound by these Product Terms and Conditions. If you do not agree with the Product Terms and Conditions do not download or submit any orders for our Products. AWM suggests that if you have any queries in relation to the Product Terms and Conditions that you seek your own independent legal advice. AWM reserves the right to change these terms and conditions from time to time and you accept that the terms and conditions contained on the website at the time of purchase of the Product shall apply to such purchase.</p>

            <p><strong>It is agreed:</strong><br />
            <strong>1.</strong> AWM agrees to supply and you agree to purchase the products (“Products”) subject to these terms and conditions (“Agreement”). The terms of this Agreement state all your rights and remedies with respect to your purchase of Products from AWM.</p>
            <p><strong>2.</strong> The Price for the Products are listed in the Price List appearing in this website from time to time. All Prices on this site are referred to in Australian dollars. Prices do not include any federal, state, municipal or other foreign government duties or taxes (such as goods and services tax , excise tax, customs duties, etc, unless otherwise stated). All such amounts will be in addition to the Price stated in this website. All payments to AWM for Products are to be made using the method prescribed. Australian residents are liable for GST on the Products unless you are able to provide a declaration that you are not in Australia at the time of making the purchase.</p>
            <p><strong>3.</strong> All Products shall be delivered by AWM to the address you have nominated on the order form. AWM are not able to deliver if you fail to provide the information required in the order form and accept no responsibility to undertake delivery unless the relevant information required by the order form has been provided. This clause relates to delivery in Australia only. A delivery to a location outside Australia will need to subject to specific agreement with AWM prior to acceptance by AWM of any such order of Products.</p>
            <p><strong>4.</strong> It is against the law to sell or supply alcohol, or to obtain alcohol, for a person under the age of 18 years. It is important that the person able to accept delivery of the alcohol being supplied as a Product by AWM is 18 years of age or older and has been authorised by you to accept receipt of the Product. To the extent necessary, you undertake to AWM by submitting the order for the Products, that you will comply with these requirements. AWM will not deliver if they consider there are any circumstances which affect or prohibit delivery, including but not limited to the age of the person receiving delivery, that the person is affect by alcohol or drugs, or are procuring the Products for any reason we consider not proper, reason or lawful. If the person to receive the Products does not verify upon a reasonable request by the AWM delivery person or agent AWM may determine, at their absolute discretion, to not deliver the Products.</p>
            <p><strong>5.</strong> AWM will seek to deliver the Products at the times nominated by you. You accept that there may be circumstances which do not allow for delivery of the Products to occur at such time and that the risk of such occurring is your rest, and AWM is not held responsible by you of the risk of non-delivery occurring at the nominated times.</p>
            <p><strong>6.</strong> If for any reason delivery cannot occur, or the Products are returned unopened to AWM by you within seven (7) days of delivery, AWM will provide you with a refund of the cost of the Products less any amount incurred by AWM during the process of facilitating the return of the Products. Alternatively, if the Product has been opened by you, and the content of the Product are found to be spoiled, upon determination by AWM, the cost of the Product will be returned to you.</p>
            <p><strong>7.</strong> Australian Consumer Law
            For all or any Products that are provided to you by AWM you are entitled to a refund or replacement of those Products in the event of major failure, as that term is defined under the Australian Consumer Law. A major failure entitles you to cancel your contract for the Product and for a refund for the unused part of the goods, or for compensation for the reduced value of the goods. The remedy under the Australian Consumer Law will be at your election. If the breach does not constitute a major failure you remain entitled to a remedy for the failure, such under the Australian Consumer Law to be provided within a reasonable time.
            Without excluding, restricting, or modifying your rights under the Australian Consumer Law or the exposure of AWM to the liabilities that attach to them under the Australian Consumer Law:<br />
            (i) AWM and associate company(s), parent company, subsidiaries, directors, shareholders, affiliates, partner companies, officers, employees, agents, representatives, partners, and licensors limits the liability it is exposed to the maximum extent permitted under applicable law (including the Australian Consumer Law) or the amount paid by you for the Product provided by AWM, whichever is the lesser. To the extent permissible, AWM disclaim all or any implied warranties that may apply to the Product whether express or implied, of merchantability, or fitness for a particular purpose. This section does not apply to anyone where disclaimer of implied warranties or the limitation of liability in contracts may not be lawfully limited.</p>
            <p><strong>8.</strong> AWM may at its absolute discretion decide to not accept or cancel an order for a Product, or advise of delivery conditions that would need to be accepted by you for delivery to occur, notwithstanding that you have made payment or that AWM has provided a tax invoice to you for the amount of the Product. Such may occur in circumstances where:<br />
            (a) a misdescription of the Product or price of the Product has occurred;<br />
            (b) the Products although advertised are not available from AWM;<br />
            (c) the terms and conditions do not allow for the delivery of the Product or to deliver would be a breach of the law.<br />
            Once you have ordered the Product you are not able to change or cancel your order. AWM may at their absolute discretion waive your obligations to complete the order if they consider the circumstances that exist justify cancellation of the order, or AWM may agree to change to your order. If you wish to cancel or change an order you should contact AWM to discuss the matter using the contact details referred to on this website.<br />
            AWM may require proof of purchase from you prior to considering whether to cancel or change any order. It may also need prior to accepting to cancel or change any order assurance by conducting an inspection of the Products that they are in their original condition or packaging.</p>
            <p><strong>9.</strong> You accept that the risk of loss or damage to the Products passes to you upon the delivery of the Product to the premises stated on your order form. The title to the Products passes to you upon their dispatch from our premises. If the Products are later returned to AWM in accordance with these terms and conditions, then the title shall pass back to AWM upon delivery of the Products to the AWM premises.</p>
            <p><strong>10.</strong> Products displayed and offered for sale on this website include products that contain alcohol. AWM is licensed under South Australian law to provide products for sale containing alcohol. [Liquor licence number 57617785]. A resident of the Northern Territory or any person ordering from this website and seeking delivery of an order to the Northern Territory should not consider the listing of a product by AWM to constitute an offer to sell the Product. AWM will need to assess the Product against the price checking mechanism in the Northern Territory to ensure the Northern Territory Minimum Unit Price Legislation has been complied with, and AWM reserves the right to amend the price to ensure compliance with such legislation notwithstanding that the price advertised on the website is different than the new price.</p>
            <p><strong>11.</strong> You must pay for your goods at the time of order. AWM use Stripe to process your credit card payment. Your complete credit card number cannot be viewed by AWM or any outside party. We never permanently store complete credit card details on site. Please visit <a href="https://stripe.com/en-au" rel="noreferrer" target="_blank">https://stripe.com/en-au</a> for more information.</p>
            <p><strong>12.</strong> To the full extent permissible under applicable law, AWM expressively disclaims all warranties express or implied of any kind with respect to the Products, including warranties of merchantability and fitness for a particular purpose. Some jurisdictions limit or do not allow the disclaimer of implied or other warranties and the above disclaimer shall not apply in those jurisdictions to the extent such laws are applicable to this Agreement.</p>
            <p><strong>13.</strong> AWM and their directors, officers, employees, consultants, agents or other representatives shall not be liable for any damage, loss or expense of any kind arising out of or resulting from your purchase of the Products regardless of whether such liability is based in tort, contract or otherwise. Some jurisdictions limit or do not allow an exclusion of liability and the above exclusion of liability shall not apply in those jurisdictions to the extent such laws are applicable to this Agreement.</p>
            <p><strong>14.</strong> To the extent applicable at law, AWM limits its liability in the case of the Product to the replacement of the product or the supply of equivalent product, or the repair of the product, or paying of the costs for replacing the product or acquiring equivalent product, or the payment of the cost of having the product repaired. If the foregoing are held to be unenforceable, the maximum liability of AWM and their directors, officers, employees, consultants, agents or other representatives to you shall not exceed the amount of the price paid by you for the Products. Some jurisdictions limit or do not allow a limitation of liability and the above limitation of liability shall not apply in those jurisdictions to the extent such laws are applicable to this Agreement.</p>
            <p><strong>15.</strong> In no event shall AWM or their directors, officers, employees, consultants, agents or other representatives be liable to you for any indirect, special, incidental, consequential or punitive damages (including without limitation loss of profits, loss or corruption of data, loss of goodwill, work stoppage, computer failure or malfunction or interruption of business), regardless of whether AWM or their directors, officers, employees, consultants, agents or other representatives have been advised of the possibility of such damages.</p>
            <p><strong>16.</strong> You represent and warrant for the benefit of AWM that you:<br />
            <strong>16.1.</strong> are 18 years of age or older;<br />
            <strong>16.2.</strong> possess the legal right and ability to enter into this Agreement and make the credit card payment on your own behalf or on behalf or any person for whom you are acting as agent and/or that you are authorised to do so; and<br />
            <strong>16.3.</strong> all information that you submit is true, accurate and current.</p>
            <p><strong>17.</strong> Whilst AWM takes every precaution in the preparation of its circulars, price lists and its other literature these documents are for your general guidance only. You acknowledge that you have not relied on any representation made by AWM which has not been stated expressly in this Agreement or upon any circulars, price lists or other literature produced by AWM. AWM employees or agents are not authorised to make any representations concerning the Products unless such representations are confirmed by AWM in writing.</p>
            <p><strong>18.</strong> You agree that in the event you have any complaint associated with AWM (including the purchase of any Products) that you will comply with the following complaint process:-<br />
            <strong>18.1.</strong> You will contact AWM forthwith and outline your complaint in writing advising all relevant details.<br />
            <strong>18.2.</strong> You will allow AWM 30 days in which to respond to your complaint in writing, and thereafter, you will enter into good faith discussions with AWM to resolve such complaint.<br />
            <strong>18.3.</strong> In the event that a satisfactory resolution to the complaint cannot be achieved, you will enter into mediation with AWM for resolution of the complaint prior to pursuing any legal action to the extent permitted by law.</p>
            <p><strong>19.</strong> If a dispute arises between the parties, including the non-resolution of a complaint as referred to in clause 18, you agree that no court proceedings in relation to the dispute will be taken by you, unless the following mediation process has been completed:-<br />
            <strong>19.1.</strong> You must advise AWM of any dispute by written notice adequately identifying and providing details of the dispute, referring to any documentary evidence of the matters claimed in the dispute and designate a representative who has authority to negotiate and settle the dispute.<br />
            <strong>19.2.</strong> Within 28 days after receiving the notice referred to in clause 19.1 AWM must respond to the notice providing details and referring to any documentary evidence in support and designate a representative who has authority to negotiate and settle the dispute.<br />
            <strong>19.3.</strong> Within 20 days of receiving the notice from AWM, you and AWM must negotiate and endeavour to settle the dispute.<br />
            <strong>19.4.</strong> If the dispute is not settled within 30 days of the attempts to negotiate and endeavour to settle the dispute as provided in clause 19.3 an independent mediator with relevant experience of the matter in dispute will be appointed by agreement, or failing agreement, a person appointed by the President of the Law Society of South Australia will be appointed to mediate the dispute.<br />
            <strong>19.5.</strong> If within two months after the date of the mediator’s appointment the dispute has not been resolved, either party may by notice in writing terminate the mediation process and seek such remedies as they decide.<br />
            <strong>19.6.</strong> Except in relation to urgent injunctive relief, you agree that you will not commence court proceedings unless you have first complied with the dispute resolution provisions contained in this clause 19. You agree that this agreement may be pleaded as a bar to any court action commenced prior to the termination of the mediation process.<br />
            <strong>19.7.</strong> In any case, you shall bear your own costs for the mediation and pay one-half of the costs of the mediator.<br />
            <strong>19.8.</strong> You acknowledge any exchange or information or documents of the making or any offer or settlement pursuant to this clause is an attempt to settle the dispute between the parties. Neither you nor AWM may use any information or documents obtained through the dispute resolution process for any other purpose.</p>
            <p><strong>20.</strong> You shall not assign or transfer or purport to assign or transfer this Agreement or the benefits thereof to any other person without the prior written consent of AWM.</p>
            <p><strong>21.</strong> AWM shall not be liable for any failure by it to perform this Agreement, or for any loss and damage suffered by you in consequence thereof which failure arises from any cause whatsoever beyond the control of AWM, including (but not being limited to) computer, communication or network failures, pandemic, fire or other accident, strikes or other labour disputes, inability of AWM’s supplier to deliver materials or finished products, any computer virus introduced by a third party to the product supplied by AWM to you, or any other law, proclamation, regulation or ordinance or any government agency.</p>
            <p><strong>22.</strong> This Agreement shall be governed by and construed in accordance with the laws in force in South Australia and all disputes arising in connection with this Agreement shall be submitted to the jurisdiction of the relevant court of South Australia. AWM has no physical presence or permanent establishment in the United States of America or any jurisdiction other than Australia.</p>
            <p><strong>23.</strong> This Agreement constitutes the entire agreement of the parties with respect to the subject matter hereof and supersedes all previous written or oral agreements between the parties with respect to such subject matter. No waiver by either party or any breach or default hereunder shall be deemed to be a waiver of any proceeding or subsequent default or breach. AWM may freely transfer, assign or delegate all or any part of this Agreement and all rights and duties thereunder, without the requirement of consent. This Agreement will be binding upon and inure to the benefits of the heirs, successors and permitted assigns of the parties. Headings and sub-headings are for clarification purposes only and do not form part of these terms and conditions.</p>
            <p><strong>24.</strong> AWM Contact Information<br />
            Australia Wine Merchants Pty Ltd<br />
            ACN 624 008 939 ABN 27 624 008 939<br />
            ‘Oaks’ at Morphettville Racecourse, Morphettville, 5043South Australia, Australia,<br />
            Telephone: <a href="tel:+61 452 560 710" style={{display: "inline"}}>+61 452 560 710</a> E-Mail: <a href="mailto:admin@awmaus.com.au" style={{display: "inline"}}>admin@awmaus.com.au</a></p>
        </div>
      </div>
    </div>
  )
}

export default ProductTerms